name: FizzBuzz CI/CD Pipeline

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define jobs
jobs:
  # Job 1: Run tests
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the latest Python 3.x version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Install pytest for running tests

      # Step 4: Run tests
      - name: Run tests
        run: |
          python -m pytest  # Run tests using pytest

  # Job 2: Lint the code (optional)
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 .  # Lint the code

  # Job 3: Build and push Docker image (optional)
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Your Docker Hub username
          password: ${{ secrets.DOCKER_HUB_TOKEN }}     # Your Docker Hub token/password

      - name: Build Docker image
        run: docker build -t yordi11/fizzbuzz:latest .  # Use your Docker Hub username

      - name: Push Docker image
        run: docker push yordi11/fizzbuzz:latest  # Use your Docker Hub username
